/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MockTesting;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

    ShoppingCart shoppingCart;
    ProductService productService;
    Product p1;
    Product p2;

    @Test
    @BeforeEach
    void initTest()
    {
        shoppingCart = new ShoppingCart();
        productService = mock(ProductService.class);
        p1 = new Product("1","RTX 3080",2);
        p2 = new Product("2","GTX 1650",4);
        ArrayList<Product> list = new ArrayList<Product>();
        shoppingCart.setProductService(productService);
        list.add(p1);
        list.add(p2);
        shoppingCart.setProducts(list);
    }

    @Test
    @DisplayName("Test getDiscout")
    void test2()
    {
        when(productService.getPrice(p1)).thenReturn(1500.0d);
        when(productService.getPrice(p2)).thenReturn(290.50d);
        when(productService.getDiscount(4162)).thenReturn(0.9d);
        assertTrue(shoppingCart.getCartValue() == 3745.8);
    }
}
