/** Generated by YAKINDU Statechart Tools code generator. */


#include "../src/sc_types.h"

#include "DigitalClock.h"

/*! \file Implementation of the state machine 'DigitalClock'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_main_region_DisplayHour_default(DigitalClock* handle);
static void enseq_main_region_DisplaySecond_default(DigitalClock* handle);
static void enseq_main_region_DisplayDate_default(DigitalClock* handle);
static void enseq_main_region_default(DigitalClock* handle);
static void exseq_main_region_DisplayHour(DigitalClock* handle);
static void exseq_main_region_DisplaySecond(DigitalClock* handle);
static void exseq_main_region_DisplayDate(DigitalClock* handle);
static void exseq_main_region(DigitalClock* handle);
static void react_main_region__entry_Default(DigitalClock* handle);

/*! State machine reactions. */
static sc_integer react(DigitalClock* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayHour. */
static sc_integer main_region_DisplayHour_react(DigitalClock* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplaySecond. */
static sc_integer main_region_DisplaySecond_react(DigitalClock* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayDate. */
static sc_integer main_region_DisplayDate_react(DigitalClock* handle, const sc_integer transitioned_before);


static void clear_in_events(DigitalClock* handle);

static void micro_step(DigitalClock* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(DigitalClock* handle);



static void digitalclock_eventqueue_init(digitalclock_eventqueue * eq, digitalclock_event *buffer, sc_integer capacity);
static sc_integer digitalclock_eventqueue_size(digitalclock_eventqueue * eq);
static void digitalclock_event_init(digitalclock_event * ev, DigitalClockEventID name);
static digitalclock_event digitalclock_eventqueue_pop(digitalclock_eventqueue * eq);
static sc_boolean digitalclock_eventqueue_push(digitalclock_eventqueue * eq, digitalclock_event ev);
static void digitalClock_add_event_to_queue(digitalclock_eventqueue * eq, DigitalClockEventID name);
static void digitalClock_dispatch_event(DigitalClock* handle, const digitalclock_event * event);
static digitalclock_event digitalClock_get_next_event(DigitalClock* handle);
static void digitalClock_dispatch_next_event(DigitalClock* handle);


void digitalClock_init(DigitalClock* handle)
{
	sc_integer i;
	
	for (i = 0; i < DIGITALCLOCK_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = DigitalClock_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart DigitalClock */
	handle->iface.hours = 0;
	handle->iface.minutes = 0;
	handle->iface.seconds = 0;
	handle->iface.dayInMonth = 0;
	handle->iface.month = 0;
	
	handle->isExecuting = bool_false;
	digitalclock_eventqueue_init(&handle->in_event_queue, handle->in_buffer, DIGITALCLOCK_IN_EVENTQUEUE_BUFFERSIZE);
}

void digitalClock_enter(DigitalClock* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart DigitalClock */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void digitalClock_exit(DigitalClock* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart DigitalClock */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean digitalClock_is_active(const DigitalClock* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < DIGITALCLOCK_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != DigitalClock_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean digitalClock_is_final(const DigitalClock* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean digitalClock_is_state_active(const DigitalClock* handle, DigitalClockStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case DigitalClock_main_region_DisplayHour :
			result = (sc_boolean) (handle->stateConfVector[SCVI_DIGITALCLOCK_MAIN_REGION_DISPLAYHOUR] == DigitalClock_main_region_DisplayHour
			);
			break;
		case DigitalClock_main_region_DisplaySecond :
			result = (sc_boolean) (handle->stateConfVector[SCVI_DIGITALCLOCK_MAIN_REGION_DISPLAYSECOND] == DigitalClock_main_region_DisplaySecond
			);
			break;
		case DigitalClock_main_region_DisplayDate :
			result = (sc_boolean) (handle->stateConfVector[SCVI_DIGITALCLOCK_MAIN_REGION_DISPLAYDATE] == DigitalClock_main_region_DisplayDate
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clear_in_events(DigitalClock* handle)
{
	handle->iface.b1_raised = bool_false;
}

static void micro_step(DigitalClock* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case DigitalClock_main_region_DisplayHour :
		{
			main_region_DisplayHour_react(handle, -1);
			break;
		}
		case DigitalClock_main_region_DisplaySecond :
		{
			main_region_DisplaySecond_react(handle, -1);
			break;
		}
		case DigitalClock_main_region_DisplayDate :
		{
			main_region_DisplayDate_react(handle, -1);
			break;
		}
		default: break;
	}
}

static void run_cycle(DigitalClock* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	digitalClock_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
		digitalClock_dispatch_next_event(handle);
	} while (handle->iface.b1_raised == bool_true);
	handle->isExecuting = bool_false;
}


void digitalClock_raise_b1(DigitalClock* handle)
{
	digitalClock_add_event_to_queue(&(handle->in_event_queue), DigitalClock_b1);
	run_cycle(handle);
}



sc_integer digitalClock_get_hours(const DigitalClock* handle)
{
	return handle->iface.hours;
}
void digitalClock_set_hours(DigitalClock* handle, sc_integer value)
{
	handle->iface.hours = value;
}
sc_integer digitalClock_get_minutes(const DigitalClock* handle)
{
	return handle->iface.minutes;
}
void digitalClock_set_minutes(DigitalClock* handle, sc_integer value)
{
	handle->iface.minutes = value;
}
sc_integer digitalClock_get_seconds(const DigitalClock* handle)
{
	return handle->iface.seconds;
}
void digitalClock_set_seconds(DigitalClock* handle, sc_integer value)
{
	handle->iface.seconds = value;
}
sc_integer digitalClock_get_dayInMonth(const DigitalClock* handle)
{
	return handle->iface.dayInMonth;
}
void digitalClock_set_dayInMonth(DigitalClock* handle, sc_integer value)
{
	handle->iface.dayInMonth = value;
}
sc_integer digitalClock_get_month(const DigitalClock* handle)
{
	return handle->iface.month;
}
void digitalClock_set_month(DigitalClock* handle, sc_integer value)
{
	handle->iface.month = value;
}

/* implementations of all internal functions */

/* 'default' enter sequence for state DisplayHour */
static void enseq_main_region_DisplayHour_default(DigitalClock* handle)
{
	/* 'default' enter sequence for state DisplayHour */
	handle->stateConfVector[0] = DigitalClock_main_region_DisplayHour;
}

/* 'default' enter sequence for state DisplaySecond */
static void enseq_main_region_DisplaySecond_default(DigitalClock* handle)
{
	/* 'default' enter sequence for state DisplaySecond */
	handle->stateConfVector[0] = DigitalClock_main_region_DisplaySecond;
}

/* 'default' enter sequence for state DisplayDate */
static void enseq_main_region_DisplayDate_default(DigitalClock* handle)
{
	/* 'default' enter sequence for state DisplayDate */
	handle->stateConfVector[0] = DigitalClock_main_region_DisplayDate;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(DigitalClock* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state DisplayHour */
static void exseq_main_region_DisplayHour(DigitalClock* handle)
{
	/* Default exit sequence for state DisplayHour */
	handle->stateConfVector[0] = DigitalClock_last_state;
}

/* Default exit sequence for state DisplaySecond */
static void exseq_main_region_DisplaySecond(DigitalClock* handle)
{
	/* Default exit sequence for state DisplaySecond */
	handle->stateConfVector[0] = DigitalClock_last_state;
}

/* Default exit sequence for state DisplayDate */
static void exseq_main_region_DisplayDate(DigitalClock* handle)
{
	/* Default exit sequence for state DisplayDate */
	handle->stateConfVector[0] = DigitalClock_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(DigitalClock* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of DigitalClock.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case DigitalClock_main_region_DisplayHour :
		{
			exseq_main_region_DisplayHour(handle);
			break;
		}
		case DigitalClock_main_region_DisplaySecond :
		{
			exseq_main_region_DisplaySecond(handle);
			break;
		}
		case DigitalClock_main_region_DisplayDate :
		{
			exseq_main_region_DisplayDate(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(DigitalClock* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_DisplayHour_default(handle);
}


static sc_integer react(DigitalClock* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_DisplayHour_react(DigitalClock* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayHour. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.b1_raised == bool_true)
		{ 
			exseq_main_region_DisplayHour(handle);
			enseq_main_region_DisplayDate_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_DisplaySecond_react(DigitalClock* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplaySecond. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.b1_raised == bool_true)
		{ 
			exseq_main_region_DisplaySecond(handle);
			enseq_main_region_DisplayHour_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_DisplayDate_react(DigitalClock* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayDate. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.b1_raised == bool_true)
		{ 
			exseq_main_region_DisplayDate(handle);
			enseq_main_region_DisplaySecond_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}




static void digitalclock_eventqueue_init(digitalclock_eventqueue * eq, digitalclock_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer digitalclock_eventqueue_size(digitalclock_eventqueue * eq)
{
	return eq->size;
}

static digitalclock_event digitalclock_eventqueue_pop(digitalclock_eventqueue * eq)
{
	digitalclock_event event;
	if(digitalclock_eventqueue_size(eq) <= 0) {
		digitalclock_event_init(&event, DigitalClock_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean digitalclock_eventqueue_push(digitalclock_eventqueue * eq, digitalclock_event ev)
{
	if(digitalclock_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void digitalclock_event_init(digitalclock_event * ev, DigitalClockEventID name)
{
	ev->name = name;
}

static void digitalClock_add_event_to_queue(digitalclock_eventqueue * eq, DigitalClockEventID name)
{
	digitalclock_event event;
	digitalclock_event_init(&event, name);
	digitalclock_eventqueue_push(eq, event);
}

static void digitalClock_dispatch_event(DigitalClock* handle, const digitalclock_event * event) {
	switch(event->name) {
		case DigitalClock_b1:
		{
			handle->iface.b1_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static digitalclock_event digitalClock_get_next_event(DigitalClock* handle)
{
	digitalclock_event next_event;
	digitalclock_event_init(&next_event, DigitalClock_invalid_event);
	if(digitalclock_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = digitalclock_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void digitalClock_dispatch_next_event(DigitalClock* handle)
{
	digitalclock_event nextEvent;
	nextEvent = digitalClock_get_next_event(handle);
	digitalClock_dispatch_event(handle, &nextEvent);
}
