/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercice5;

import Exercice5.statepattern.DigitalClock;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

public class App extends Application {

    DigitalClock dcStatePattern = new DigitalClock();
    GridPane gp1 = new GridPane();
    

    Text t1 = new Text("heur:minute:seconds");

    Button btnB1 = new Button("b1");
    Button btnB2 = new Button("b2");
    Button btnB3 = new Button("b3");

    public String getGreeting() {
        return "Hello World!";
    }

//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }

    @Override
    public void start(Stage stage) {
        btnB1.setOnAction(new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent event) {
                System.out.println("Button b1 pressed");
                dcStatePattern.b1();
                dcStatePattern.display(); 
            }
        });

        gp1.setMinSize(640, 480);

        gp1.add(btnB1, 0, 1);
        gp1.add(btnB2, 1, 1);
        gp1.add(btnB3, 2, 1);
        gp1.add(t1, 0, 0);

        Scene scene = new Scene(new StackPane(gp1));
        stage.setScene(scene);
        stage.show();
    }

    

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    protected void finalize() throws Throwable {
        super.stop();
    }
}
